#tomcat server config
server:
  port: 8080
  address: 127.0.0.1
  servlet:
      context-path: /spt
#access-log\u65E5\u5FD7\u8BB0\u5F55
  tomcat:
    basedir: 'D:/work'
    accesslog:
      enabled: true
      directory: 'D:/work'
      pattern: '%t [%I] %{X-Forwarded-For}i %a %r %s (%D ms)'
      prefix: access_log

#\u542F\u7528\u5BF9\u5E94\u914D\u7F6E\u6587\u4EF6
spring:
  profiles:
    active: dev


#\u6D4B\u8BD5\u81EA\u5B9A\u4E49\u53C2\u6570
custom:
  msg:defautl-msg
  num:${custom.num}